#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        NXSDataSources.py
#
#  Project :     Collection of NeXus DataSources
#
# This file is part of Tango device class.
#
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
#
#
#  $Author :      jankotan$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__docformat__ = 'restructuredtext'


try:
    import tango
except Exception:
    import PyTango as tango

from .DataSources import DataSources as DS


class NXSDataSources(tango.LatestDeviceImpl):
    """Provides a collection of NeXus datasources as Tango attributes"""

    def __init__(self, cl, name):
        """  Device constructor

        :param cl: class name
        :type cl: :obj:`str`
        :param name: device name
        :type name: :obj:`str`
        """
        tango.LatestDeviceImpl.__init__(self, cl, name)
        self.debug_stream("In __init__()")
        #: (:class:`nxsrecconfig.Settings.Settings`) \
        #:     DataSources Collection
        self.__ds = None
        #: (:class:`tango.DeviceProxy`) self device proxy
        self.__dp = None
        NXSDataSources.init_device(self)

    def delete_device(self):
        self.debug_stream("In delete_device()")
        if self.__ds:
            self.__ds = None
        self.set_state(tango.DevState.OFF)

    def init_device(self):
        self.debug_stream("In init_device()")
        if self.__ds:
            self.__ds = None
        self.__dp = self.__dp or tango.DeviceProxy(self.get_name())
        self.get_device_properties(self.get_device_class())
        self.__ds = DS(self, self.NXSConfigServer or None, self.__dp,
                       self.DSBlackList or [])
        self.set_state(tango.DevState.ON)

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")

    # -------------------------------------------------------------------------
    #    NXSDataSources read/write attribute methods
    # -------------------------------------------------------------------------

    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")

    # -------------------------------------------------------------------------
    #    NXSDataSources command methods
    # -------------------------------------------------------------------------
    def AddDataSources(self, argin):
        """ adds NeXus datasources attributes from NXSConfigServer
        :param argin: list of DataSource names
        :type argin: tango.DevVarStringArray
        """
        self.debug_stream("In AddDataSources()")
        try:
            self.set_state(tango.DevState.RUNNING)
            self.__ds.addDataSources(argin)
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)

    def is_AddDataSources_allowed(self):
        """ AddDataSources command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def RemoveDataSources(self, argin):
        """ removes NeXus datasources attributes from NXSConfigServer
        :param argin: list of DataSource names
        :type argin: tango.DevVarStringArray
        """
        self.debug_stream("In RemoveDataSources()")
        try:
            self.set_state(tango.DevState.RUNNING)
            self.__ds.removeDataSources(argin)
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)

    def is_RemoveDataSources_allowed(self):
        """ RemoveDataSources command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def AvailableDataSources(self):
        """ AvailableDataSources command

        :brief: Return a list of available DataSource names
        :returns: DevVarStringArray    list of available DataSource names
        :rtype: :obj:`list` <:obj:`str`>
        """
        self.debug_stream("In AvailableDataSources()")
        try:
            self.set_state(tango.DevState.RUNNING)
            argout = self.__ds.availableDataSources()
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)

        return argout

    def is_AvailableDataSources_allowed(self):
        """ AvailableDataSources command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def SetVariables(self, argin):
        """ sets  XML configuration varialbes from the given JSON string
        :param argin: JSON string with XML configuration varialbes
        :type argin: tango.DevString
        """
        self.debug_stream("In SetVariables()")
        self.debug_stream("In RemoveDataSources()")
        try:
            self.set_state(tango.DevState.RUNNING)
            self.__ds.setVariables(argin)
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)

    def is_SetVariables_allowed(self):
        """ SetVariables command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def SetCommonBlock(self, argin):
        """ set  CommonBlock from the given JSON string
        :param argin: JSON string with CommonBlock
        :type argin: tango.DevString
        """
        self.debug_stream("In SetCommonBlock()")
        try:
            self.set_state(tango.DevState.RUNNING)
            self.__ds.setCommonBlock(argin)
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)

    def is_SetCommonBlock_allowed(self):
        """ SetCommonBlock command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def Variables(self):
        """ Provides  JSON string with XML configuration variables
        :return: JSON string with XML configuration variables
        :rtype: tango.DevString
        """
        self.debug_stream("In Variables()")
        try:
            self.set_state(tango.DevState.RUNNING)
            argout = self.__ds.variables()
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)
        return argout

    def is_Variables_allowed(self):
        """ Variables command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def CommonBlock(self):
        """ Provides  JSON string with the CommonBlock dictionary
        :return: JSON string with the CommonBlock dictionary
        :rtype: tango.DevString
        """
        self.debug_stream("In CommonBlock()")
        try:
            self.set_state(tango.DevState.RUNNING)
            argout = self.__ds.commonBlock()
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)
        return argout

    def is_CommonBlock_allowed(self):
        """ CommonBlock command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def Description(self):
        """ provides datasource description list
        :return: datasource descirption
        :rtype: tango.DevString
        """
        self.debug_stream("In Description()")
        try:
            self.set_state(tango.DevState.RUNNING)
            argout = self.__ds.description()
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)
        return argout

    def is_Description_allowed(self):
        """ Description command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def Refresh(self):
        """ Refresh datasource description
        """
        self.debug_stream("In Refresh()")
        try:
            self.set_state(tango.DevState.RUNNING)
            self.__ds.refresh()
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)

    def is_Refresh_allowed(self):
        """ Refresh command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def UserData(self):
        """ provide user data dictionary
        :return: user data dictionary
        :rtype: tango.DevString
        """
        self.debug_stream("In UserData()")
        try:
            self.set_state(tango.DevState.RUNNING)
            argout = self.__ds.userData()
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)
        return argout

    def is_UserData_allowed(self):
        """ UserData command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True

    def SetUserData(self, argin):
        """ set UserData from the given JSON string
        :param argin: JSON string with UserData
        :type argin: tango.DevString
        """
        self.debug_stream("In SetUserData()")
        try:
            self.set_state(tango.DevState.RUNNING)
            self.__ds.setUserData(argin)
            self.set_state(tango.DevState.ON)
        finally:
            if self.get_state() == tango.DevState.RUNNING:
                self.set_state(tango.DevState.ON)

    def is_SetUserData_allowed(self):
        """ SetUserData command State Machine

        :returns: True if the operation allowed
        :rtype: :obj:`bool`
        """
        if self.get_state() in [tango.DevState.RUNNING]:
            return False
        return True


class NXSDataSourcesClass(tango.DeviceClass):

    #    Class Properties
    class_property_list = {
        }

    #    Device Properties
    device_property_list = {
        'NXSConfigServer':
            [tango.DevString,
             "NeXus configuration server",
             [],
             ],
        'TangoDSPrefix':
            [tango.DevString,
             "Prefix for Tango DataSources",
             ["ds_"],
             ],
        'PyEvalDSPrefix':
            [tango.DevString,
             "Prefix for PyEval DataSources",
             ["ds_"],
             ],
        'ClientDSPrefix':
            [tango.DevString,
             "Prefix for Cient DataSources",
             ["ds_"],
             ],
        'DbDSPrefix':
            [tango.DevString,
             "Prefix for Database DataSources",
             ["ds_"],
             ],
        'DSBlackList':
            [tango.DevVarStringArray,
             "datasource black list",
             [],
             ],
    }

    #    Command definitions
    cmd_list = {
        'AddDataSources':
            [[tango.DevVarStringArray, "list of DataSource names"],
             [tango.DevVoid, "none"]],
        'RemoveDataSources':
            [[tango.DevVarStringArray, "list of DataSource names"],
             [tango.DevVoid, "none"]],
        'AvailableDataSources':
            [[tango.DevVoid, "none"],
             [tango.DevVarStringArray, "list of  exposed datasources"]],
        'SetVariables':
            [[tango.DevString, "JSON string with XML configuration varialbes"],
             [tango.DevVoid, "none"]],
        'SetCommonBlock':
            [[tango.DevString, "JSON string with CommonBlock"],
             [tango.DevVoid, "none"]],
        'Variables':
            [[tango.DevVoid, "none"],
             [tango.DevString,
              "JSON string with XML configuration variables"]],
        'CommonBlock':
            [[tango.DevVoid, "none"],
             [tango.DevString, "JSON string with the CommonBlock dictionary"]],
        'Description':
            [[tango.DevVoid, "none"],
             [tango.DevString, "datasource descirption"]],
        'Refresh':
            [[tango.DevVoid, "none"],
             [tango.DevVoid, "none"]],
        'UserData':
            [[tango.DevVoid, "none"],
             [tango.DevString, "user data dictionary"]],
        'SetUserData':
            [[tango.DevString, "JSON string with UserData"],
             [tango.DevVoid, "none"]],
        }

    # Attribute definitions
    attr_list = {
    }


if __name__ == '__main__':
    pass
